version: '3.8'

services:
  toolbox:
    image: us-central1-docker.pkg.dev/database-toolbox/toolbox/toolbox:0.12.0
    container_name: mcp-toolbox
    expose:
      - "5000"
    volumes:
      # Google Cloud credentials
      - ./application-default-credentials.json:/app/application-default-credentials.json:ro
      # Tools configuration
      - ./toolbox.yaml:/app/toolbox.yaml:ro
    environment:
      # Set Google Cloud credentials
      - GOOGLE_APPLICATION_CREDENTIALS=/app/application-default-credentials.json
      # Optional: Set port if needed (default is 5000)
      - PORT=5000
    command: ["--tools-file", "/app/toolbox.yaml","--address", "0.0.0.0","--port", "5000"]
    restart: unless-stopped
    networks:
      - toolbox-network

  nginx:
    image: nginx:alpine
    container_name: mcp-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # SSL certificates
      - ~/ssl:/etc/nginx/ssl:ro
      # Nginx configuration
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - toolbox
    restart: unless-stopped
    networks:
      - toolbox-network

networks:
  toolbox-network:
    driver: bridge
